### ISSUE TITLE
pypi jasmine package fails to install "ValueError: bad marshal data (unknown type code)"

### ISSUE THREAD

**Issue by kbeyls** [jasmine/jasmine-py#30]
When I add the jasmine pypi package as a dependency in a python package I'm working on, by adding 'jasmine' to the install_requires list in setup.py, I get the long backtrace below when running this on OSX, with python 2.7.10 installed under homebrew.

The error only occurs when trying to install the jasmine package as a dependency when running "python setup.py". "pip install jasmine" works just fine.

FWIW, the install_requires list looks as follows:
     install_requires=['WTForms',
                       'Flask-WTF',
                       'Flask-RESTful',
                       'SQLAlchemy',
                       'Flask',
                       'jasmine'],

$ python ../lnt/setup.py develop
....
Installed /Users/kribey01/dev/llvm.org/lnt
Processing dependencies for LNT==0.4.1.dev0
Searching for jasmine
Reading https://pypi.python.org/simple/jasmine/
Best match: jasmine 2.4.0
Downloading https://pypi.python.org/packages/b0/37/91d46bd39e0fc111c48729e1eb57a728554f7073097dae9623f899c7b0e6/jasmine-2.4.0.tar.gz#md5=810c1f22fc2ce70729bc76ef1caa4e10
Processing jasmine-2.4.0.tar.gz
Writing /var/folders/th/cnt0054d153g3xf5rt87856x_1kq80/T/easy_install-mrtBCH/jasmine-2.4.0/setup.cfg
Running jasmine-2.4.0/setup.py -q bdist_egg --dist-dir /var/folders/th/cnt0054d153g3xf5rt87856x_1kq80/T/easy_install-mrtBCH/jasmine-2.4.0/egg-dist-tmp-RSqbPL
warning: no files found matching '*.py' under directory '.'
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "../lnt/setup.py", line 113, in <module>
    ext_modules = [cPerf],
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
....
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
    run_setup(setup_script, args)
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 139, in resume
    compat.reraise(type, exc, self._tb)
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/var/folders/th/cnt0054d153g3xf5rt87856x_1kq80/T/easy_install-pVipdH/jasmine-2.4.0/setup.py", line 51, in <module>

  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 208, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 244, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 354, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/Users/kribey01/dev/llvm.org/lnt-test-runs/venv-lnt-testjasmin/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 391, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

**Comment by kbeyls** [comment]
https://github.com/tomchristie/django-rest-framework/issues/1357 seems to be a bug report of a very similar looking problem an another python package.
https://github.com/tomchristie/django-rest-framework/issues/1236 also looks similar.
https://github.com/tomchristie/django-rest-framework/issues/1804 is another similar-looking problem.

It seem the root cause may be the presence of .pyc files in the package.

The last link above suggests adding to following to MANIFEST.in to avoid the issue, and then recreating the pypi package.
```
recursive-exclude * __pycache__
recursive-exclude * *.py[co]

```

**Comment by Gerg** [comment]
I just pushed 2.5.0 with you suggested change. Let me know if it works.

**Comment by kbeyls** [comment]
Thanks Gerg - the issue was indeed fixed :)

I now encounter 2 other bugs, but they're either in Selenium or phantomjs as present on Ubuntu 16.04.
Probably nothing jasmine-py can do about. Just writing down here in case others would also run into this:
* selenium (used by jasmine-py to invoke browsers), doesn't seem to work with Firefox 47+, see
https://github.com/jasmine/jasmine-py/issues/30#issuecomment-247203785
* phantomjs on Ubuntu 16.04: Unable to load Atom 'find_elements' on Ubuntu 16.04 
https://bugs.launchpad.net/ubuntu/+source/phantomjs/+bug/1578444
