### ISSUE TITLE
Build fails with Werkzeug-0.11.11 

### ISSUE THREAD

**Issue by mikaoelitiana** [jasmine/jasmine-py#33]
I am using jasmine-py to run build on Travis-CI and the build fails as jasmine-py require version `Werkzeug==0.11.1`. Will I need to explicitly require this version in my project (this is a flask project)?

```
The command "python featreq_tests.py" exited with 0.
0.09s$ jasmine-ci
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/jasmine-ci", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Werkzeug==0.11.1
The command "jasmine-ci" exited with 1.
```

Thanks

**Comment by Gerg** [comment]
There was in issue with Werkzeug that caused us to need to pin it's version: https://github.com/jasmine/jasmine-py/commit/c5e6db65a08f889eaf448b19f48ff424fb63605a

We should be able to remove this version requirement now, though I'm not sure why you are running into this issue since it is a package dependency.
