### ISSUE TITLE
init command fails with TypeError

### ISSUE THREAD

**Issue by Fierozen** [jasmine/jasmine-py#51]
I see that issue #48 was already raised about this and that a commit was made to fix it. I will use that fix. Now I'll see if I can close this issue. 

After installing jasmine and trying to run init, I am getting this error:
(FACT) F:\HEAT\heat\cortex>jasmine init
Traceback (most recent call last):
  File "c:\users\jblack\appdata\local\continuum\anaconda3\envs\fact\lib\runpy.py", line 193, in
 _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jblack\appdata\local\continuum\anaconda3\envs\fact\lib\runpy.py", line 85, in
_run_code
    exec(code, run_globals)
  File "C:\Users\jblack\AppData\Local\Continuum\anaconda3\envs\FACT\Scripts\jasmine.exe\__main_
_.py", line 9, in <module>
  File "c:\users\jblack\appdata\local\continuum\anaconda3\envs\fact\lib\site-packages\jasmine\e
ntry_points.py", line 15, in begin
    cmd.run(sys.argv[1:])
  File "c:\users\jblack\appdata\local\continuum\anaconda3\envs\fact\lib\site-packages\jasmine\e
ntry_points.py", line 64, in run
    args.func(args)
TypeError: init() takes 1 positional argument but 2 were given

This is on Windows 10
I have Python 3.6 in a conda environment. Is that the problem? Do you only support 3.5?

**Comment by Fierozen** [comment]
This issue was already reported and addressed as #48.

**Comment by beatorizu** [comment]
I got the same issue. To fix I added args argument to init def in `entry_points.py`

**Comment by slackersoft** [comment]
The fix for this has already been merged, but hasn't been released yet.

**Comment by beatorizu** [comment]
Thanks :D

**Comment by slackersoft** [comment]
Jasmine 3.1.1 is out (https://pypi.org/project/jasmine/) and should include this fix. Sorry for the delay

**Comment by beatorizu** [comment]
Yay! I will test 🙌
